HOSTS:
  debian11-64:
    docker_cmd:
      - "/sbin/init"
    image: debian:11
    platform: debian-11-amd64
    packaging_platform: debian-11-amd64
    docker_image_commands:
      - cp /bin/true /sbin/agetty
      - rm -f /usr/sbin/policy-rc.d
      - apt-get update && apt-get install -y cron locales-all net-tools wget systemd-sysv
        gnupg
    hypervisor: docker
